name: Metrics (dashboard)

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sdey1122
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 14

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_achievements: yes
          plugin_achievements_threshold: C

          output_action: commit
          committer_message: "chore: update metrics"
          filename: metrics.svg
          target: metrics
